steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/auth-service:latest"
      - "."
    dir: "services/auth"

  # Push Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA"

  # Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/auth-service:latest"

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "auth-service"
      - "--image=gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--cpu=1"
      - "--memory=512Mi"
      - "--min-instances=1"
      - "--max-instances=10"
      - "--set-env-vars=NODE_ENV=production"
      - "--set-secrets=JWT_SECRET=JWT_SECRET:latest,SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_SERVICE_KEY=SUPABASE_SERVICE_KEY:latest,ALLOWED_ORIGINS=ALLOWED_ORIGINS:latest"

images:
  - "gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/auth-service:latest"

options:
  machineType: "N1_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
