steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/interprecoach:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/interprecoach:latest"
      - "-f"
      - "Dockerfile"
      - "."
    dir: "services/interpreCoach"

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/interprecoach:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/interprecoach:latest"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "interprecoach"
      - "--image"
      - "gcr.io/$PROJECT_ID/interprecoach:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--port"
      - "80"
      - "--set-env-vars"
      - "NODE_ENV=production"

images:
  - "gcr.io/$PROJECT_ID/interprecoach:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/interprecoach:latest"

options:
  machineType: "N1_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
