steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--network=cloudbuild'
  - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/interprelab-repo/interprelab-eco-landing-page'
  - '--build-arg'
  - 'VITE_SUPABASE_URL=$$VITE_SUPABASE_URL'
  - '--build-arg'
  - 'VITE_SUPABASE_PUBLISHABLE_KEY=$$VITE_SUPABASE_PUBLISHABLE_KEY'
  - '.'
  secretEnv:
  - 'VITE_SUPABASE_URL'
  - 'VITE_SUPABASE_PUBLISHABLE_KEY'
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/interprelab-repo/interprelab-eco-landing-page'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/VITE_SUPABASE_URL/versions/latest
    env: 'VITE_SUPABASE_URL'
  - versionName: projects/$PROJECT_ID/secrets/VITE_SUPABASE_PUBLISHABLE_KEY/versions/latest
    env: 'VITE_SUPABASE_PUBLISHABLE_KEY'
