# Google Cloud Run Service Configuration
# This file can be used with: gcloud run services replace service.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: interprelab-landing
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # Autoscaling
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"

        # CPU allocation
        run.googleapis.com/cpu-throttling: "true"

        # Startup probe
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: PROJECT_NUMBER-compute@developer.gserviceaccount.com
      containers:
        - name: interprelab-landing
          image: gcr.io/PROJECT_ID/interprelab-landing:latest
          ports:
            - name: http1
              containerPort: 80
          env:
            - name: NODE_ENV
              value: production
          # Add your environment variables here
          # - name: VITE_SUPABASE_URL
          #   valueFrom:
          #     secretKeyRef:
          #       name: supabase-url
          #       key: latest
          resources:
            limits:
              cpu: "1000m"
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
