import { useState, useEffect, useCallback, useMemo } from "react";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "@/components/ui/card";
import {
  Lightbulb,
  TrendingUp,
  AlertTriangle,
  Loader2,
  Sparkles,
} from "lucide-react";

// Constants for better maintainability
const INSIGHT_ROTATION_INTERVAL = 5000; // 5 seconds
const COMPONENT_TITLE = "AI-Powered Insights";
const COMPONENT_DESCRIPTION = "Your performance summary generated by AI.";

// Default insights when no AI-generated content is available
const DEFAULT_INSIGHTS = [
  {
    id: "encouragement",
    text: "You're doing great! Keep up the good work.",
    type: "positive" as const,
    icon: TrendingUp,
  },
  {
    id: "wellness",
    text: "You've had a busy week! Make sure to take a break.",
    type: "neutral" as const,
    icon: Lightbulb,
  },
  {
    id: "achievement",
    text: "Your earnings are up this week! Congratulations!",
    type: "positive" as const,
    icon: Sparkles,
  },
] as const;

// Types for better type safety
interface Insight {
  id: string;
  text: string;
  type: "positive" | "neutral" | "warning";
  icon: React.ComponentType<React.SVGProps<SVGSVGElement>>;
}

interface AIInsightsProps {
  /** AI-generated statistics or insights content */
  stats: string | null;
  /** Whether there's an error with AI service */
  error?: boolean;
  /** Optional custom insights to display */
  customInsights?: Insight[];
}

/**
 * Card Header Component
 * Displays the consistent header for all AI insights states
 */
const InsightsHeader = () => (
  <CardHeader>
    <CardTitle className="flex items-center gap-2">
      <Lightbulb className="text-primary h-5 w-5" />
      {COMPONENT_TITLE}
    </CardTitle>
    <CardDescription>{COMPONENT_DESCRIPTION}</CardDescription>
  </CardHeader>
);

/**
 * Error State Component
 * Displays when AI features are disabled or there's an API error
 */
const ErrorState = () => (
  <Card className="h-full flex flex-col">
    <InsightsHeader />
    <CardContent className="flex-grow flex flex-col items-center justify-center text-center space-y-4">
      <AlertTriangle className="w-12 h-12 text-destructive" />
      <div className="space-y-2">
        <h3 className="font-semibold text-foreground">AI Features Disabled</h3>
        <p className="text-sm text-muted-foreground max-w-sm">
          To enable AI-powered insights, please add your Gemini API key to the{" "}
          <code className="bg-muted px-1.5 py-1 rounded-sm text-xs font-mono">
            .env
          </code>{" "}
          file.
        </p>
      </div>
    </CardContent>
  </Card>
);

/**
 * Loading State Component
 * Displays while AI insights are being generated
 */
const LoadingState = () => (
  <Card className="h-full flex flex-col">
    <InsightsHeader />
    <CardContent className="flex-grow flex flex-col items-center justify-center space-y-4">
      <Loader2 className="w-8 h-8 text-primary animate-spin" />
      <p className="text-sm text-muted-foreground">Generating AI insights...</p>
    </CardContent>
  </Card>
);

/**
 * Insight Display Component
 * Shows individual insight with appropriate styling and icon
 */
interface InsightDisplayProps {
  insight: Insight;
  isVisible: boolean;
}

const InsightDisplay = ({ insight, isVisible }: InsightDisplayProps) => {
  const Icon = insight.icon;

  const getInsightStyles = (type: Insight["type"]) => {
    switch (type) {
      case "positive":
        return "border-l-green-500 bg-green-50/50 dark:bg-green-950/20";
      case "warning":
        return "border-l-yellow-500 bg-yellow-50/50 dark:bg-yellow-950/20";
      case "neutral":
      default:
        return "border-l-primary bg-primary/10";
    }
  };

  return (
    <div
      className={`
        transition-all duration-500 ease-in-out
        ${
          isVisible
            ? "opacity-100 transform translate-y-0"
            : "opacity-0 transform translate-y-2"
        }
      `}
    >
      <div
        className={`
        text-center p-6 border-l-4 rounded-r-lg
        ${getInsightStyles(insight.type)}
      `}
      >
        <div className="flex items-center justify-center mb-3">
          <Icon className="w-5 h-5 text-primary" />
        </div>
        <p className="text-muted-foreground italic text-lg leading-relaxed">
          "{insight.text}"
        </p>
      </div>
    </div>
  );
};

/**
 * Insight Rotation Indicator
 * Shows dots indicating current insight and total count
 */
interface RotationIndicatorProps {
  currentIndex: number;
  totalCount: number;
}

const RotationIndicator = ({
  currentIndex,
  totalCount,
}: RotationIndicatorProps) => {
  if (totalCount <= 1) return null;

  return (
    <div className="flex justify-center space-x-2 mt-4">
      {Array.from({ length: totalCount }, (_, index) => (
        <div
          key={index}
          className={`
            w-2 h-2 rounded-full transition-colors duration-300
            ${index === currentIndex ? "bg-primary" : "bg-muted-foreground/30"}
          `}
        />
      ))}
    </div>
  );
};

/**
 * Custom hook for managing insight rotation
 * Handles automatic cycling through insights with proper cleanup
 */
const useInsightRotation = (
  insights: readonly Insight[],
  isActive: boolean = true
) => {
  const [currentIndex, setCurrentIndex] = useState(0);

  const rotateToNext = useCallback(() => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % insights.length);
  }, [insights.length]);

  const rotateToIndex = useCallback(
    (index: number) => {
      if (index >= 0 && index < insights.length) {
        setCurrentIndex(index);
      }
    },
    [insights.length]
  );

  useEffect(() => {
    if (!isActive || insights.length <= 1) return;

    const intervalId = setInterval(rotateToNext, INSIGHT_ROTATION_INTERVAL);
    return () => clearInterval(intervalId);
  }, [rotateToNext, isActive, insights.length]);

  // Reset index if insights array changes
  useEffect(() => {
    if (currentIndex >= insights.length) {
      setCurrentIndex(0);
    }
  }, [insights.length, currentIndex]);

  return {
    currentIndex,
    currentInsight: insights[currentIndex],
    rotateToNext,
    rotateToIndex,
  };
};

/**
 * Custom hook for processing AI insights
 * Handles parsing and formatting of AI-generated content
 */
const useProcessedInsights = (
  stats: string | null,
  customInsights?: Insight[]
) => {
  return useMemo(() => {
    // If custom insights are provided, use them
    if (customInsights && customInsights.length > 0) {
      return customInsights;
    }

    // If AI stats are available, process them
    if (stats) {
      // TODO: Implement AI stats parsing logic here
      // For now, return default insights with AI-generated content
      return [
        {
          id: "ai-generated",
          text: stats,
          type: "neutral" as const,
          icon: Sparkles,
        },
      ];
    }

    // Fall back to default insights
    return DEFAULT_INSIGHTS;
  }, [stats, customInsights]);
};

/**
 * AI Insights Component
 *
 * A comprehensive AI-powered insights display system that provides:
 * - Real-time performance analysis and recommendations
 * - Automatic insight rotation with smooth transitions
 * - Multiple display states (loading, error, content)
 * - Customizable insights with different types and styling
 * - Visual indicators for insight navigation
 *
 * Features:
 * - Automatic rotation every 5 seconds
 * - Smooth fade transitions between insights
 * - Type-based styling (positive, neutral, warning)
 * - Loading and error state handling
 * - Responsive design with proper accessibility
 * - Support for both AI-generated and custom insights
 *
 * @param stats - AI-generated statistics or insights content
 * @param error - Whether there's an error with AI service
 * @param customInsights - Optional custom insights to display instead of defaults
 */
export default function AIInsights({
  stats,
  error,
  customInsights,
}: AIInsightsProps) {
  const processedInsights = useProcessedInsights(stats, customInsights);
  const { currentIndex, currentInsight } = useInsightRotation(
    processedInsights,
    !error
  );

  // Handle error state
  if (error) {
    return <ErrorState />;
  }

  // Handle loading state
  if (!stats && !customInsights) {
    return <LoadingState />;
  }

  // Handle empty insights
  if (processedInsights.length === 0) {
    return <LoadingState />;
  }

  return (
    <Card className="w-full">
      <InsightsHeader />
      <CardContent className="flex flex-col justify-center space-y-4 min-h-[200px]">
        <InsightDisplay insight={currentInsight} isVisible={true} />
        <RotationIndicator
          currentIndex={currentIndex}
          totalCount={processedInsights.length}
        />
      </CardContent>
    </Card>
  );
}
